// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrZJahEWJbdkrjZDz_ttKs4HnWfh5OIN0',
    appId: '1:894667091574:web:c487b8ead8912ae895f957',
    messagingSenderId: '894667091574',
    projectId: 'smarttask-9ea31',
    authDomain: 'smarttask-9ea31.firebaseapp.com',
    storageBucket: 'smarttask-9ea31.firebasestorage.app',
    measurementId: 'G-GR0RKLS8VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH2pcHp5XQJ5_eU24g6B2bV_xtMHQ5rUU',
    appId: '1:894667091574:android:4525ce7d8582ec6595f957',
    messagingSenderId: '894667091574',
    projectId: 'smarttask-9ea31',
    storageBucket: 'smarttask-9ea31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnGSylpR2KjKda9pV06ix6fZI7Gf1RW2M',
    appId: '1:894667091574:ios:e31bda21acb7ce1795f957',
    messagingSenderId: '894667091574',
    projectId: 'smarttask-9ea31',
    storageBucket: 'smarttask-9ea31.firebasestorage.app',
    iosBundleId: 'com.example.smartTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnGSylpR2KjKda9pV06ix6fZI7Gf1RW2M',
    appId: '1:894667091574:ios:e31bda21acb7ce1795f957',
    messagingSenderId: '894667091574',
    projectId: 'smarttask-9ea31',
    storageBucket: 'smarttask-9ea31.firebasestorage.app',
    iosBundleId: 'com.example.smartTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrZJahEWJbdkrjZDz_ttKs4HnWfh5OIN0',
    appId: '1:894667091574:web:ae8451bfa0f405b495f957',
    messagingSenderId: '894667091574',
    projectId: 'smarttask-9ea31',
    authDomain: 'smarttask-9ea31.firebaseapp.com',
    storageBucket: 'smarttask-9ea31.firebasestorage.app',
    measurementId: 'G-DP9EXRX3DP',
  );
}
